replicaCount: 1

image:
  repository: signalen/classification
  tag: ""
  pullPolicy: IfNotPresent

signalsCategoryUrl: https://backend.signalen.demoground.nl/signals/v1/public/terms
modelsDirectory: /models

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 65534 # Make persistent volume writable for container user

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: classification.signals.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: classification-tls
      hosts:
        - classification.signals.local

persistence:
  enabled: true
  size: 1Gi
  existingClaim: null
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumes: []
extraVolumeMounts: []
